
export enum PackFlag {
    HidePackIcon = 1
}

export enum PartFlag1 {
    RestrictOppositeGender = 1 << 7,
    AllowForLiveRandom = 1 << 6,
    ShowInCasDemo = 1 << 5,
    ShowInSimInfoPanel = 1 << 4,
    ShowInUI = 1 << 3,
    AllowForCasRandom = 1 << 2,
    DefaultThumbnailPart = 1 << 1,
    DefaultForBodyType = 1,
}

export enum PartFlag2 {
    Unknown4 = 1 << 7,
    Unknown3 = 1 << 6,
    Unknown2 = 1 << 5,
    CreatedInGame = 1 << 4,
    Unknown1 = 1 << 3,
    DefaultForBodyTypeFemale = 1 << 2,
    DefaultForBodyTypeMale = 1 << 1,
    RestrictOppositeFrame = 1,
}

export enum AgeGenderFlag {
    BABY = 1,
    TODDLER = 2,
    CHILD = 4,
    TEEN = 8,
    YOUNG_ADULT = 16,
    ADULT = 32,
    ELDER = 64,
    MALE = 4096,
    FEMALE = 8192,
}

export enum Species {
    HUMAN = 1,
    DOG = 2,
    CAT = 3,
    SMALL_DOG = 4,
    FOX = 5,
}

export enum BodyType {
    NONE = 0,
    HAT = 1,
    HAIR = 2,
    HEAD = 3,
    TEETH = 4,
    FULL_BODY = 5,
    UPPER_BODY = 6,
    LOWER_BODY = 7,
    SHOES = 8,
    CUMMERBUND = 9,
    EARRINGS = 10,
    GLASSES = 11,
    NECKLACE = 12,
    GLOVES = 13,
    WRIST_LEFT = 14,
    WRIST_RIGHT = 15,
    LIP_RING_LEFT = 16,
    LIP_RING_RIGHT = 17,
    NOSE_RING_LEFT = 18,
    NOSE_RING_RIGHT = 19,
    BROW_RING_LEFT = 20,
    BROW_RING_RIGHT = 21,
    INDEX_FINGER_LEFT = 22,
    INDEX_FINGER_RIGHT = 23,
    RING_FINGER_LEFT = 24,
    RING_FINGER_RIGHT = 25,
    MIDDLE_FINGER_LEFT = 26,
    MIDDLE_FINGER_RIGHT = 27,
    FACIAL_HAIR = 28,
    LIPS_TICK = 29,
    EYE_SHADOW = 30,
    EYE_LINER = 31,
    BLUSH = 32,
    FACEPAINT = 33,
    EYEBROWS = 34,
    EYECOLOR = 35,
    SOCKS = 36,
    MASCARA = 37,
    SKINDETAIL_CREASE_FOREHEAD = 38,
    SKINDETAIL_FRECKLES = 39,
    SKINDETAIL_DIMPLE_LEFT = 40,
    SKINDETAIL_DIMPLE_RIGHT = 41,
    TIGHTS = 42,
    SKINDETAIL_MOLE_LIP_LEFT = 43,
    SKINDETAIL_MOLE_LIP_RIGHT = 44,
    TATTOO_ARM_LOWER_LEFT = 45,
    TATTOO_ARM_UPPER_LEFT = 46,
    TATTOO_ARM_LOWER_RIGHT = 47,
    TATTOO_ARM_UPPER_RIGHT = 48,
    TATTOO_LEG_LEFT = 49,
    TATTOO_LEG_RIGHT = 50,
    TATTOO_TORSO_BACK_LOWER = 51,
    TATTOO_TORSO_BACK_UPPER = 52,
    TATTOO_TORSO_FRONT_LOWER = 53,
    TATTOO_TORSO_FRONT_UPPER = 54,
    SKINDETAIL_MOLE_CHEEK_LEFT = 55,
    SKINDETAIL_MOLE_CHEEK_RIGHT = 56,
    SKINDETAIL_CREASE_MOUTH = 57,
    SKIN_OVERLAY = 58,
    FUR_BODY = 59,
    EARS = 60,
    TAIL = 61,
    SKINDETAIL_NOSE_COLOR = 62,
    EYECOLOR_SECONDARY = 63,
    OCCULT_BROW = 64,
    OCCULT_EYE_SOCKET = 65,
    OCCULT_EYE_LID = 66,
    OCCULT_MOUTH = 67,
    OCCULT_LEFT_CHEEK = 68,
    OCCULT_RIGHT_CHEEK = 69,
    OCCULT_NECK_SCAR = 70,
    FOREARM_SCAR = 71,
    ACNE = 72,
    FINGERNAIL = 73,
    TOENAIL = 74,
    HAIRCOLOR_OVERRIDE = 75,
    BITE = 76,
    UNUSED1 = 77,
    BODYHAIR_ARM = 78,
    BODYHAIR_LEG = 79,
    BODYHAIR_TORSOFRONT = 80,
    BODYHAIR_TORSOBACK = 81,
    BODYSCAR_ARMLEFT = 82,
    BODYSCAR_ARMRIGHT = 83,
    BODYSCAR_TORSOFRONT = 84,
    BODYSCAR_TORSOBACK = 85,
    BODYSCAR_LEGLEFT = 86,
    BODYSCAR_LEGRIGHT = 87,
    SKINDETAIL_ACNE_PUBERTY = 89,
}

export enum BodySubType {
    NONE = 0,
    EARS_UP = 1,
    EARS_DOWN = 2,
    TAIL_LONG = 3,
    TAIL_RING = 4,
    TAIL_SCREW = 5,
    TAIL_STUB = 6,
}

export enum OccultType {
    SPELLCASTER = 1 << 4,
    MERMAID = 1 << 3,
    VAMPIRE = 1 << 2,
    ALIEN = 1 << 1,
    HUMAN = 1,
}
